version: "3"

services:
    web:
        build:
            context: web
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        environment:
            - PUBLIC_BACKEND_ADDRESS=ws://localhost:3000
        ports:
            - 5173:5173
        volumes:
            - ./web:/app
            - /app/node_modules
    backend:
        build:
            context: backend
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        environment:
            - PORT=3000
            - CORS_ORIGIN=*
            - RABBIT_URL=amqp://rabbit
            - GAME_SERVER_URL=ws://host.docker.internal:4890
        ports:
            - 3000:3000
        volumes:
            - ./backend:/app
            - /app/node_modules
        extra_hosts:
          - host.docker.internal:host-gateway
        depends_on:
            rabbit:
                condition: service_healthy
    matchmaking:
        build:
            context: matchmaking
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        environment:
            - RABBIT_URL=amqp://rabbit
        depends_on:
            rabbit:
                condition: service_healthy
    rabbit:
        image: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
        healthcheck:
              test: rabbitmq-diagnostics -q ping
              interval: 5s
              timeout: 10s
              retries: 5

