[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
mlua = { version = "0.9.3", features = ["lua54", "async", "send"] }
uuid = "1.6.1"
tokio = { version = "1.36.0", features = ["macros", "rt"] }
